version: '3'

services:
  master:
    build: .
    command:
      - roscore

  talker:
    build: .
    environment:
      - "ROS_HOSTNAME=talker"
      - "ROS_MASTER_URI=http://master:11311"
    depends_on:
      - master
    command:
      - rosrun roscpp_tutorials talker

  listener:
    build: .
    environment:
      - "ROS_HOSTNAME=listener"
      - "ROS_MASTER_URI=http://master:11311"
    depends_on:
      - master
    command:
      - rosrun roscpp_tutorials listener
